// Handles mobile menu toggling and keeps ARIA state synchronized.
const navToggle = document.getElementById('navToggle');
const siteNav = document.getElementById('siteNav');

if (navToggle && siteNav) {
  navToggle.addEventListener('click', () => {
    const isOpen = siteNav.classList.toggle('show');
    navToggle.setAttribute('aria-expanded', String(isOpen));
  });
}

// Lightweight newsletter validation with immediate feedback.
const signupForm = document.getElementById('signupForm');
const emailInput = document.getElementById('email');
const formMessage = document.getElementById('formMessage');

if (signupForm && emailInput && formMessage) {
  signupForm.addEventListener('submit', (event) => {
    event.preventDefault();
    const email = emailInput.value.trim();

    if (!email || !email.includes('@') || !email.includes('.')) {
      formMessage.style.color = '#ff9b9b';
      formMessage.textContent = 'Please enter a valid email address.';
      return;
    }

    formMessage.style.color = '#6af7a6';
    formMessage.textContent = 'You are on the list. Welcome to Infinite Dimensions.';
    signupForm.reset();
  });
}

// Printful catalog rendering. It pulls from a local JSON file generated by
// scripts/sync_printful_products.py so the storefront stays static, fast, and safe.
const merchGrid = document.getElementById('merchGrid');
const merchStatus = document.getElementById('merchStatus');
const merchLastUpdated = document.getElementById('merchLastUpdated');

function renderMerchCards(products) {
  if (!merchGrid) {
    return;
  }

  merchGrid.innerHTML = '';

  products.forEach((product) => {
    const card = document.createElement('article');
    card.className = 'merch-card';

    const title = document.createElement('h3');
    title.textContent = `🛒 ${product.title}`;

    const description = document.createElement('p');
    description.textContent = product.description || 'Fresh from the Infinite Dimensions merch vault.';

    const image = document.createElement('img');
    image.loading = 'lazy';
    image.src = product.image || 'https://via.placeholder.com/600x600/111327/f3f5ff?text=Merch';
    image.alt = product.title;

    const footer = document.createElement('div');
    footer.className = 'merch-card-footer';

    const price = document.createElement('span');
    price.className = 'price';
    price.title = 'Starting price from your Printful listing';
    price.textContent = product.price_display || 'From $--';

    const link = document.createElement('a');
    link.className = 'btn btn-ghost';
    link.textContent = 'View product ↗';

    if (product.product_url) {
      link.href = product.product_url;
      link.target = '_blank';
      link.rel = 'noreferrer noopener';
      link.title = 'Open product details in a new tab';
    } else {
      // Keeps UI transparent when a listing has no public storefront URL yet.
      link.href = '#';
      link.setAttribute('aria-disabled', 'true');
      link.classList.add('disabled-link');
      link.title = 'Publish/connect this product to a sales channel to enable public links';
    }

    footer.append(price, link);
    card.append(image, title, description, footer);
    merchGrid.appendChild(card);
  });
}

async function loadMerchCatalog() {
  if (!merchGrid || !merchStatus || !merchLastUpdated) {
    return;
  }

  try {
    const response = await fetch('data/printful-products.json', { cache: 'no-store' });

    if (!response.ok) {
      throw new Error(`Catalog request failed with ${response.status}`);
    }

    const catalog = await response.json();
    const products = Array.isArray(catalog.products) ? catalog.products : [];

    if (!products.length) {
      merchStatus.textContent = '⚠️ No products found yet. Run the Printful sync script to populate catalog data.';
      return;
    }

    renderMerchCards(products);
    merchStatus.textContent = `✅ Showing ${products.length} products from your latest Printful sync.`;

    const syncedAt = catalog.last_synced ? new Date(catalog.last_synced) : null;
    merchLastUpdated.textContent = syncedAt && !Number.isNaN(syncedAt.valueOf())
      ? `Last sync: ${syncedAt.toLocaleString()}`
      : 'Last sync: Unknown';
  } catch (error) {
    merchStatus.textContent = '⚠️ Unable to load merch catalog. Confirm data/printful-products.json exists and is valid JSON.';
    merchLastUpdated.textContent = 'Last sync: unavailable';
    console.error('Failed to load merch catalog', error);
  }
}

loadMerchCatalog();

// Automatically keeps the footer year current.
const year = document.getElementById('year');
if (year) {
  year.textContent = new Date().getFullYear();
}
