<?php

declare(strict_types=1);

/**
 * Admin panel authentication configuration.
 *
 * Set password_hash to a value generated by password_hash('your-password', PASSWORD_DEFAULT).
 * Leave empty to keep admin panel locked.
 */
return [
    'password_hash' => '',
];
